apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      labels: python-admission
  template:
    metadata:
      labels:
        app: python-admission
    spec:
      serviceAcoountName: admission-python
      containers:
        - name: python-admission
          image: webhook:v1
          ports:
            - containerPort: 8001
    