apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod2
  labels:
    app: myapp
    type: front-end

spec:
  containers:
    - name: busybox
      image: busybox
      command:
        [
          "sh",
          "-c",
          "while true; do echo New radom number is $(( ( RANDOM % 100 )  + 1 )); sleep 2; done",
        ]
