apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysimple-app-deploy
  labels:
    app: go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:    
      containers:
      - name: goserver
        image: keys4words/goserver:1.0