apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deploy"
  labels:
    app: go-server
spec:
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:    
      containers:
      - name: goserver
        image: "{{ .Values.deploy.image.repository }}:{{ .Chart.AppVersion }}"