apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
        env:
        - name: GUNICORN_CMD_ARGS
          value: "--capture-output --error-logfile -
                  --access-logfile - --access-logformat '%(h)s %(t)s
                  %(r)s %(s)s Host: %({Host}i)s}'"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: second-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin
        ports:
        - containerPort: 80
        env:
        - name: GUNICORN_CMD_ARGS
          value: "--capture-output --error-logfile -
                  --access-logfile - --access-logformat '%(h)s %(t)s
                  %(r)s %(s)s Host: %({Host}i)s}'"
---
apiVersion: v1
kind: Service
metadata:
  name: first-service
spec:
  selector:
    app: first-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: second-service
spec:
  selector:
    app: second-app
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apps-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
  labels:
    name: apps-ingress
spec:
  rules:
    - host: myhost.com
      http:
        paths:
          - pathType: Prefix
            path: "/anything"
            backend:
              service:
                name: first-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/uuid"
            backend:
              service:
                name: second-service
                port:
                  number: 80
