apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-default
  labels:
    app: kuber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server-default
  template:
    metadata:
      labels:
        app: http-server-default
    spec:
      containers:
      - name: kuber-app
        image: keys4words/pingserver:2.0
        command: ["python3","-u","server-default.py"]
        # args: ["2", "4", "kubic forever"]
        args: ["GPU"]
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-default-service
spec:
  selector:
    app: http-server-default
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30001
  type: NodePort